### ISSUE TITLE
adding user at rocket chat not possible

### ISSUE THREAD

**Issue by Hocklebock** [wechange-eg/cosinnus-devops#50]
Hey there,

thanks for your platform. Much appriciated. However, there is a bug when trying to add a user which user name consist only of two letters e.g. lr to a channel

![image](https://user-images.githubusercontent.com/38473205/114918203-1cdb9d80-9e27-11eb-9b62-353cbb09cf75.png)

also not possible to find the user via the display name

![image](https://user-images.githubusercontent.com/38473205/114918424-5c09ee80-9e27-11eb-9616-7476cdb994c7.png)

Hope you can fix that soon!

Cheers,

Jan

**Comment by saschasommer** [comment]
@Hocklebock hi Jan!

I'm afraid that since these problems are part of RocketChat's core functionality, we can't change much about this. We do however always keep our rocketchat service up-to date, so you could raise this issue with them https://github.com/RocketChat/Rocket.Chat/issues. If they publish the change, it will soon pop up on the Wechange Rocketchat as well!

Cheers, Sascha
