### ISSUE TITLE
Service 'web' failed to build...

### ISSUE THREAD

**Issue by armantorkzaban** [wechange-eg/cosinnus-devops#52]
I tried the docker-compose up and got the error below: 
```
Step 13/16 : WORKDIR /code/cosinnus-core
 ---> Using cache
 ---> 8896ace89399
Step 14/16 : RUN npm i --production && npm run production
 ---> Running in 207748d511ab
npm WARN npm npm does not support Node.js v8.17.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! URL is not defined
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-24T15_51_10_539Z-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm i --production && npm run production' returned a non-zero code: 1
```

Any suggestion which configuration should be changed and where?

**Comment by simonline** [comment]
Hi @armantorkzaban, the Docker specific files within this repository have been created during a Hackathon in 2018 and updated by our community. Since the WECHANGE core developers currently don't use Docker in development/production stack, we cannot offer any support related to Docker. However you can always get in contact with other developers which might also use Docker in our discord channel at https://discord.gg/pX2TJMM. We'll be glad to review and accept your pull requests.

**Comment by armantorkzaban** [comment]
Alright then. I will start with the manual installation in order to test the environment. As I get into the details I will try to update the Docker.
